##
## Made by	db0
## Contact	db0company@gmail.com
## Website	http://db0.fr/
##

MAKE		=	make

all		:
#			@ (cd $(LIST) && $(MAKE))
clean		:
#			@ (cd $(LIST) && $(MAKE) clean)

fclean		:
#			@ (cd $(LIST) && $(MAKE) fclean)

re		:	fclean all
